apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-task-app
  template:
    metadata:
      labels:
        app: brain-task-app
    spec:
      containers:
        - name: brain-task-app
          image: 866945988845.dkr.ecr.us-east-1.amazonaws.com/brain-task-app:latest
          ports:
            - containerPort: 3000
