apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
  namespace: brain-tasks
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000

